# Generated by Django 4.0.5 on 2023-07-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('marca', models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='Ford', max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serial_carro', models.CharField(max_length=50, verbose_name='Serial Carrocería')),
                ('serial_motor', models.CharField(max_length=50, verbose_name='Serial Motor')),
                ('categoria', models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], default='Particular', max_length=20, verbose_name='Categoría')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'ordering': ['marca'],
            },
        ),
    ]
