# Generated by Django 4.0.5 on 2023-07-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_remove_vehiculo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['created'], 'permissions': (('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos'),), 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
