# Generated by Django 4.0.5 on 2023-07-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['created'], 'permissions': (('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos'), ('can_add_vehiculo', 'Puede agregar Vehículos')), 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
